FROM bayesimpact/ruby-2.2.3-phantomjs

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /bridge
WORKDIR /bridge
COPY Gemfile /bridge/Gemfile
COPY Gemfile.lock /bridge/Gemfile.lock
RUN bundle install --with=test

COPY . /bridge
RUN sed -i -e "s/localhost:/testdb:/" /bridge/config/aws.yml
ENTRYPOINT ["bundle", "exec", "rspec", "--profile", "20", "--format", "documentation"]
