"""Generates a Ruby file that contains police ORI data."""

import sys
from collections import defaultdict

import pandas as pd


def process(infile, outfile):
    """Read data from infile and generate js at outfile."""
    outlines = [
        "# This file was automatically generated by a rule in the Makefile",
        "module Constants",
        "  CONTRACTING_ORIS = {",
    ]
    df = pd.read_csv(infile)
    agency_to_contracts = defaultdict(list)
    for sub, parent in zip(df['ORI'], df['CONTRACTS_TO_ORI']):
        if pd.isnull(parent) or parent == '':
            continue
        agency_to_contracts[parent].append(sub)

    for parent in sorted(agency_to_contracts):
        subs = sorted(agency_to_contracts[parent])
        outlines.append('    "%s" => %%w(%s),' % (parent, " ".join(subs)))

    outlines[-1] = outlines[-1][:-1]
    outlines.extend([
        "  }.freeze",
        "end"])
    with open(outfile, 'w') as f:
        f.write('\n'.join(outlines) + '\n')


def main(infile, outfile):
    """Usually should not need to change this method, but do so as needed."""
    print('Creating {} ...'.format(outfile))
    process(infile, outfile)
    print('...success!')


if __name__ == '__main__':
    main(*sys.argv[1:])
