"""Generates a javascript file that contains police ORI data."""

import csv
import sys


def process(infile, outfile):
    """Read data from infile and generate js at outfile."""
    outlines = [
        "// This file was automatically generated by a rule in the Makefile",
        "window.AGENCY_ORI = [",
    ]
    with open(infile) as f:
        reader = csv.reader(f)
        header = True
        for line in reader:
            if header:
                header = False
            else:
                outlines.append('  "%s",' % ", ".join(line[:3]))
    outlines.append("]")
    with open(outfile, 'w') as f:
        f.write('\n'.join(outlines) + '\n')


def main(infile, outfile):
    """Usually should not need to change this method, but do so as needed."""
    print('Creating {} ...'.format(outfile))
    process(infile, outfile)
    print('...success!')


if __name__ == '__main__':
    main(*sys.argv[1:])
